language: c++
compiler: clang
addons:
  apt:
    packages:
    - cmake

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake .. 
     - make
